/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedItemAddRouteImport } from './routes/_authenticated/item/add'
import { Route as AuthenticatedItemItemIdRouteImport } from './routes/_authenticated/item/$itemId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemAddRoute = AuthenticatedItemAddRouteImport.update({
  id: '/item/add',
  path: '/item/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemItemIdRoute = AuthenticatedItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof SignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/item/$itemId': typeof AuthenticatedItemItemIdRoute
  '/item/add': typeof AuthenticatedItemAddRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/item/$itemId': typeof AuthenticatedItemItemIdRoute
  '/item/add': typeof AuthenticatedItemAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/item/$itemId': typeof AuthenticatedItemItemIdRoute
  '/_authenticated/item/add': typeof AuthenticatedItemAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-in' | '/' | '/item/$itemId' | '/item/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/' | '/item/$itemId' | '/item/add'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/'
    | '/_authenticated/item/$itemId'
    | '/_authenticated/item/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/item/add': {
      id: '/_authenticated/item/add'
      path: '/item/add'
      fullPath: '/item/add'
      preLoaderRoute: typeof AuthenticatedItemAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/item/$itemId': {
      id: '/_authenticated/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof AuthenticatedItemItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedItemItemIdRoute: typeof AuthenticatedItemItemIdRoute
  AuthenticatedItemAddRoute: typeof AuthenticatedItemAddRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedItemItemIdRoute: AuthenticatedItemItemIdRoute,
  AuthenticatedItemAddRoute: AuthenticatedItemAddRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
